version: '3.1'

services:

 db:

   image: mariadb

   restart: always

   environment:

     MYSQL_ROOT_PASSWORD: root

     MYSQL_DATABASE: testdb

   ports:

     - 3306:3306



 adminer:

   image: adminer

   restart: always

   ports:

     - 8080:8080



 spring-boot-rest-app:

   image: spring-boot-rest-app

   command: java -jar app.jar

   restart: always

   build:

     context: ./

     dockerfile: Dockerfile

   depends_on:

     - db

   ports:

     - 8082:8082

   environment:

     - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/testdb

     - SPRING_DATASOURCE_USERNAME=root

     - SPRING_DATASOURCE_PASSWORD=root